### ISSUE TITLE
ERROR: the following packages/stacks could not have their rosdep keys resolved to system dependencies:" on rosdep install [Windows 10]

### ISSUE THREAD

**Issue by mericgeren** [fkie/multimaster_fkie#192]
Hello,

I am using Windows 10, ROS Noetic and Python 3.8.3 and trying install multimaster_fkie. I have entered the commands `pip install grpcio` and `pip install grpcio-tools`. Then, moved into "src" folder in my catkin workspace and entered `git clone https://github.com/fkie/multimaster_fkie.git multimaster` command. I did `rosdep update` and it worked without any issue. But, when i enter the command `rosdep install -i --as-root pip:false --reinstall --from-paths multimaster` i get following message:

> C:\my_catkin_wp\src>rosdep install -i --as-root pip:false --reinstall --from-paths multimaster
> ERROR: the following packages/stacks could not have their rosdep keys resolved
> to system dependencies:
> fkie_master_discovery: No definition of [avahi-daemon] for OS [windows]
> fkie_node_manager_daemon: No definition of [screen] for OS [windows]
> fkie_multimaster_msgs: No definition of [python3-grpc-tools] for OS [windows]
> fkie_node_manager: No definition of [xterm] for OS [windows]

Then, i run the command `catkin build fkie_multimaster` and got this output:

```
catkin build fkie_multimaster
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "c:\opt\ros\noetic\x64\Scripts\catkin.exe\__main__.py", line 7, in <module>
  File "c:\opt\ros\noetic\x64\lib\site-packages\catkin_tools\commands\catkin.py", line 265, in main
    catkin_main(sysargs)
  File "c:\opt\ros\noetic\x64\lib\site-packages\catkin_tools\commands\catkin.py", line 164, in catkin_main
    argument_preprocessors = create_subparsers(parser, verbs)
  File "c:\opt\ros\noetic\x64\lib\site-packages\catkin_tools\commands\catkin.py", line 56, in create_subparsers
    desc = load_verb_description(verb)
  File "c:\opt\ros\noetic\x64\lib\site-packages\catkin_tools\commands\catkin.py", line 43, in load_verb_description
    return entry_point.load()
  File "c:\opt\ros\noetic\x64\lib\site-packages\pkg_resources\__init__.py", line 2447, in load
    return self.resolve()
  File "c:\opt\ros\noetic\x64\lib\site-packages\pkg_resources\__init__.py", line 2453, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\opt\ros\noetic\x64\lib\site-packages\catkin_tools\verbs\catkin_build\__init__.py", line 15, in <module>
    from catkin_tools.argument_parsing import argument_preprocessor
  File "c:\opt\ros\noetic\x64\lib\site-packages\catkin_tools\argument_parsing.py", line 22, in <module>
    from .execution import job_server
  File "c:\opt\ros\noetic\x64\lib\site-packages\catkin_tools\execution\job_server.py", line 16, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'
```

Could you help me on this issue please?

**Comment by atiderko** [comment]
Hi, I am sorry this package was not developed for Windows.
